# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  maildev = {
    pname = "maildev";
    version = "v2.1.0";
    src = fetchFromGitHub {
      owner = "maildev";
      repo = "maildev";
      rev = "v2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-lTLhQ+gKQvfagKp0Ig+uOGwkUtzORaY1TzIkFOcoO3I=";
    };
  };
  stripe-mock = {
    pname = "stripe-mock";
    version = "v0.183.0";
    src = fetchFromGitHub {
      owner = "stripe";
      repo = "stripe-mock";
      rev = "v0.183.0";
      fetchSubmodules = false;
      sha256 = "sha256-hdcINPrlE4bjSCOUJG64Ok1gz+jwYhf2RzT+eBK7dPM=";
    };
  };
}
